- name: Build and Sign
  run: |
    xcodebuild clean archive \
      -project OmronLibrarySample.xcodeproj \
      -scheme OmronLibrarySample \
      -configuration Daily \
      -archivePath $PWD/build/OmronLibrarySample.xcarchive \
      DEVELOPMENT_TEAM="${{ secrets.DEVELOPER_TEAM_ID }}" \
      -allowProvisioningUpdates

- name: Export .ipa file
  run: |
    xcodebuild -exportArchive \
      -archivePath $PWD/build/OmronLibrarySample.xcarchive \
      -exportPath $PWD/build \
      -exportOptionsPlist ExportOptions.plist

- name: Verify .ipa file
  run: |
    ls -lh $PWD/build

- name: Authenticate Apple Account
  run: |
    xcrun altool --validate-app -f $PWD/build/OmronLibrarySample.ipa -t ios \
      -u ${{ secrets.APPLE_ID }} \
      -p ${{ secrets.APPLE_APP_PASSWORD }}
