name: Build and Sign iOS App

on:
  push:
    branches:
      - rex/github-action-setup
  pull_request:
    branches:
      - rex/github-action-setup

jobs:
  build-and-sign:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Xcode version
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      # Step 3: Decode signing credentials
      - name: Decode signing certificate
        run: |
          echo "${{ secrets.SIGNING_CERTIFICATE }}" | base64 --decode > Certificate.p12
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > Profile.mobileprovision

      # Step 4: Install signing certificate
      - name: Install signing certificate
        run: |
          # Create and unlock the keychain
          security create-keychain -p "" build.keychain
          security unlock-keychain -p "" build.keychain
          security list-keychain -s build.keychain
          security default-keychain -s build.keychain
          security set-keychain-settings

          security list-keychain
          security find-identity -p codesigning
          ls -l Certificate.p12

          # Import the .p12 file
          security import Certificate.p12 -k build.keychain -P ${{ secrets.P12_PASSWORD }} -A
          
      - name: Debug keychain
        run: |
          security list-keychain
          security find-identity -p codesigning
          ls -l Certificate.p12


      # Step 5: Install provisioning profile
      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\\ Profiles
          cp Profile.mobileprovision ~/Library/MobileDevice/Provisioning\\ Profiles/

      # Step 6: Build and sign the app
      - name: Build and Sign
        run: |
          xcodebuild clean archive \
            -project OmronLibrarySample.xcodeproj \
            -scheme OmronLibrarySample \
            -configuration Daily \
            -archivePath $PWD/build/OmronLibrarySample.xcarchive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="ProfileName" \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPER_TEAM_ID }}"
